# frozen_string_literal: true

source "https://rubygems.org"

# Specify your gem's dependencies in ipgeobase.gemspec
gemspec

gem "addressable"
gem "minitest", "~> 5.0"
gem "nokogiri-happymapper"
gem "rake", "~> 13.0"
gem "rubocop", "~> 1.7"
gem "webmock"
